markdown: kramdown

nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html
